[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["yak"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --cov=yak --cov-report=html"
pythonpath = ["."]
testpaths = ["tst"]
